# Site settings
name: Kshitij Singh
title: Kshitij Singh | Full Stack Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://kshitij.mytrashcode.com
baseurl: ''
email: kshitij@mytrashcode.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://mytrashcode.com/kshitij/resume.pdf
social:
  - title: email
    url: mailto:kshitij@mytrashcode.com
  - title: twitter
    url: https://twitter.com/ikshitijsingh
  - title: instagram
    url: https://instagram.com/singh_kshitij/
  - title: github
    url: https://github.com/singhkshitij
  - title: linkedin
    url: https://www.linkedin.com/in/ikshitijsingh/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
